name: book_viewer
description: A Flutter app to view books one by one using PageView.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/images/
