// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPpfOagp0Rgumth4KXc8g9PWRPc84Y7gc',
    appId: '1:865724121902:web:de5da4f1ed0eff0651f0bf',
    messagingSenderId: '865724121902',
    projectId: 'midtermauth',
    authDomain: 'midtermauth.firebaseapp.com',
    storageBucket: 'midtermauth.firebasestorage.app',
    measurementId: 'G-8PBHB4MM83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Azlc6r8PBh1ZV9Y4c4mY2jwwr1L-f48',
    appId: '1:865724121902:android:0c5b005764ccbbd951f0bf',
    messagingSenderId: '865724121902',
    projectId: 'midtermauth',
    storageBucket: 'midtermauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp2OCPFhxrEbxIcPEy0zv5lpCJYhpWxgw',
    appId: '1:865724121902:ios:abc9c7ddaa04d4b151f0bf',
    messagingSenderId: '865724121902',
    projectId: 'midtermauth',
    storageBucket: 'midtermauth.firebasestorage.app',
    iosBundleId: 'com.example.midtermProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp2OCPFhxrEbxIcPEy0zv5lpCJYhpWxgw',
    appId: '1:865724121902:ios:abc9c7ddaa04d4b151f0bf',
    messagingSenderId: '865724121902',
    projectId: 'midtermauth',
    storageBucket: 'midtermauth.firebasestorage.app',
    iosBundleId: 'com.example.midtermProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPpfOagp0Rgumth4KXc8g9PWRPc84Y7gc',
    appId: '1:865724121902:web:5dfc2b1993d13d3b51f0bf',
    messagingSenderId: '865724121902',
    projectId: 'midtermauth',
    authDomain: 'midtermauth.firebaseapp.com',
    storageBucket: 'midtermauth.firebasestorage.app',
    measurementId: 'G-T4Z9PJJVP9',
  );
}
