import '../models/book.dart';

class BookService {
  Future<List<Book>> fetchBooks() async {
    await Future.delayed(Duration(seconds: 1)); // simulate network delay

    return [
      Book(
        id: '1',
        title: 'Flutter for Beginners',
        author: 'Jane Doe', 
        price: 20.0,
        category: 'Programming',
        pageCount: 200,
        coverImage: 'https://m.media-amazon.com/images/I/71yHsyWh4-L.jpg',
      ),
      Book(
        id: '2',
        title: 'Advanced Dart',
        author: 'John Smith', 
        price: 25.0,
        category: 'Programming',
        pageCount: 300,
        coverImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTT2TGR6wztYcrFrnE6Q2XykoJFuc174xyR9Q&s',
      ),
      Book(
        id: '3',
        title: '1984',
        author: 'George Orwell', 
        price: 15.0,
        category: 'Science Fiction',
        pageCount: 328,
        coverImage: 'https://m.media-amazon.com/images/I/71rpa1-kyvL._AC_UF1000,1000_QL80_.jpg',
      ),
      Book(
        id: '4',
        title: 'To Kill a Mockingbird',
        author: 'Harper Lee', 
        price: 12.99,
        category: 'Classic',
        pageCount: 281,
        coverImage: 'https://m.media-amazon.com/images/I/71FxgtFKcQL._AC_UF1000,1000_QL80_.jpg',
      ),
      Book(
        id: '5',
        title: 'Pride and Prejudice',
        author: 'Jane Austen', 
        price: 8.99,
        category: 'Romance, Classic',
        pageCount: 279,
        coverImage: "https://m.media-amazon.com/images/I/81a3sr-RgdL.jpg",
      ),
      Book(
        id: '6',
        title: 'The Catcher in the Rye',
        author: 'J.D. Salinger', 
        price: 11.99,
        category: 'Fiction',
        pageCount: 277,
        coverImage: "https://m.media-amazon.com/images/I/8125BDk3l9L._AC_UF1000,1000_QL80_.jpg",
      ),
      Book(
        id: '7',
        title: 'The Lord of the Rings',
        author: 'J.R.R. Tolkien', 
        price: 15.99,
        category: 'Fantasy',
        pageCount: 1178,
        coverImage: "https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_.jpg",
      ),
      Book(
        id: '8',
        title: 'Harry Potter and the Sorcerer\'s Stone',
        author: 'J.K. Rowling', 
        price: 14.99,
        category: 'Fantasy, Children',
        pageCount: 309,
        coverImage: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1598823299i/42844155.jpg",
      ),
      Book(
        id: '9',
        title: 'The Hunger Games',
        author: 'Suzanne Collins', 
        price: 10.99,
        category: 'Dystopian, Adventure',
        pageCount: 374,
        coverImage: "https://m.media-amazon.com/images/I/71un2hI4mcL.jpg",
      ),
      Book(
        id: '10',
        title: 'The Alchemist',
        author: 'Paulo Coelho', 
        price: 13.99,
        category: 'Fiction, Adventure',
        pageCount: 208,
        coverImage: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1654371463i/18144590.jpg",
      ),
      Book(
        id: '11',
        title: 'Moby-Dick',
        author: 'Herman Melville', 
        price: 12.49,
        category: 'Classic, Adventure',
        pageCount: 635,
        coverImage: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781625584595/moby-dick-9781625584595_hr.jpg",
      ),
      Book(
        id: '12',
        title: 'The Chronicles of Narnia',
        author: 'C.S. Lewis', 
        price: 20.99,
        category: 'Fantasy, Children',
        pageCount: 768,
        coverImage: "https://rukminim2.flixcart.com/image/850/1000/kgl5ua80/book/2/6/1/moby-dick-or-the-whale-original-imafwsh4gt7ffufp.jpeg?q=90&crop=false",
      ),
      Book(
        id: '13',
        title: 'The Road',
        author: 'Cormac McCarthy', 
        price: 12.99,
        category: 'Post-apocalyptic, Fiction',
        pageCount: 287,
        coverImage: "https://m.media-amazon.com/images/M/MV5BMTAwNzk4NTU3NDReQTJeQWpwZ15BbWU3MDg3OTEyODI@._V1_FMjpg_UX1000_.jpg",
      ),
      Book(
        id: '14',
        title: 'Brave New World',
        author: 'Aldous Huxley', 
        price: 9.49,
        category: 'Dystopian, Science Fiction',
        pageCount: 268,
        coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQn17S3Zr28ei6V1vJMuYltRWRfeF3K-cgVOQ&s",
      ),
      Book(
        id: '15',
        title: 'The Shining',
        author: 'Stephen King', 
        price: 14.99,
        category: 'Horror, Fiction',
        pageCount: 447,
        coverImage: "https://m.media-amazon.com/images/M/MV5BNmM5ZThhY2ItOGRjOS00NzZiLWEwYTItNDgyMjFkOTgxMmRiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      ),
    ];
  }
}
