// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDLp_bay6Upj7QEmuXJd-CO1UspOyK9GQ',
    appId: '1:128921980097:web:601cddc15686fcf17c5840',
    messagingSenderId: '128921980097',
    projectId: 'auth-firebase-58f4c',
    authDomain: 'auth-firebase-58f4c.firebaseapp.com',
    storageBucket: 'auth-firebase-58f4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARvCSnHkLFgIoZ7FjpuTv2UYFq04I3BPw',
    appId: '1:128921980097:android:745ffacf3494d9017c5840',
    messagingSenderId: '128921980097',
    projectId: 'auth-firebase-58f4c',
    storageBucket: 'auth-firebase-58f4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu2ldr4T-DMD6Nf_iUiGRhsvPHdQ-7C2w',
    appId: '1:128921980097:ios:3b3513d77e339abb7c5840',
    messagingSenderId: '128921980097',
    projectId: 'auth-firebase-58f4c',
    storageBucket: 'auth-firebase-58f4c.firebasestorage.app',
    iosBundleId: 'com.example.calculatorAppAuthFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu2ldr4T-DMD6Nf_iUiGRhsvPHdQ-7C2w',
    appId: '1:128921980097:ios:3b3513d77e339abb7c5840',
    messagingSenderId: '128921980097',
    projectId: 'auth-firebase-58f4c',
    storageBucket: 'auth-firebase-58f4c.firebasestorage.app',
    iosBundleId: 'com.example.calculatorAppAuthFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDLp_bay6Upj7QEmuXJd-CO1UspOyK9GQ',
    appId: '1:128921980097:web:28897dc28c8a6f6d7c5840',
    messagingSenderId: '128921980097',
    projectId: 'auth-firebase-58f4c',
    authDomain: 'auth-firebase-58f4c.firebaseapp.com',
    storageBucket: 'auth-firebase-58f4c.firebasestorage.app',
  );
}
